language: node_js
node_js:
  - "8"
before_install:
    - npm i -g gulp typescript tslint
cache:
  directories:
    - "node_modules"
script:
    - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  fqdn: www.tautvydas.info
  on:
    branch: master